[package]
name = "ren"
version = "0.8.0"
edition = "2021"

[build-dependencies]
bindgen = "0.61"

[dependencies]
slotmap = "1.0"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
ash = "0.37"
ash-window = "0.12"
raw-window-handle = "0.5"
winit = "0.27"
