[package]
name = "ren"
version = "0.5.0"
edition = "2021"

[build-dependencies]
bindgen = "0.61.0"

[dependencies]
thiserror = "1.0.38"

[dev-dependencies]
anyhow = "1.0.68"
ash = "0.37"
ash-window = "0.12"
raw-window-handle = "0.5"
winit = "0.27"
